name: Update README with Latest Repo

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest repo and update README
        run: |
          # Get the latest repository name
          LATEST=$(curl -s "https://api.github.com/users/KamalSDhami/repos?sort=updated&direction=desc&per_page=5" | jq -r '.[0].name')
          echo "Latest repository: $LATEST"
          
          # Check if we got a valid repository name
          if [ "$LATEST" != "null" ] && [ -n "$LATEST" ]; then
            # Replace all instances of {{LATEST_REPO}} with the actual repo name
            sed -i "s/{{LATEST_REPO}}/$LATEST/g" README.md
            echo "Successfully updated README.md with latest repo: $LATEST"
          else
            echo "Error: Could not fetch latest repository name"
            exit 1
          fi
          
          # Show the updated content for verification
          echo "Updated section:"
          grep -A 1 -B 1 "Most Recent Repository" README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Get the latest repo name again for commit message
          LATEST=$(curl -s "https://api.github.com/users/KamalSDhami/repos?sort=updated&direction=desc&per_page=5" | jq -r '.[0].name')
          
          git add README.md
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🤖 Auto-update: Latest repository is now $LATEST"
            git push
            echo "Successfully pushed changes"
          fi
